CREATE TABLE fact_charges (
    charge_sk BIGSERIAL PRIMARY KEY,

    partner_sk INTEGER REFERENCES dim_partners(partner_sk),
    months_charge_date_sk INTEGER REFERENCES dim_months_charge_dates(months_charge_date_sk),
    customer_sk INTEGER REFERENCES dim_customers(customer_sk),
    meter_sk INTEGER REFERENCES dim_meters(meter_sk),
    product_sk INTEGER REFERENCES dim_products(product_sk),
    sku_sk INTEGER REFERENCES dim_skus(sku_sk),
    publisher_sk INTEGER REFERENCES dim_publishers(publisher_sk),
    subscription_sk INTEGER REFERENCES dim_subscriptions(subscription_sk),
    resource_location_sk INTEGER REFERENCES dim_resource_locations(resource_location_sk),
    resource_group_sk INTEGER REFERENCES dim_resource_groups(resource_group_sk),
    service_sk INTEGER REFERENCES dim_services(resource_service_sk),
    charge_type_sk INTEGER REFERENCES dim_charge_types(charge_type_sk),
    unit_type_sk INTEGER REFERENCES dim_unit_types(unit_type_sk),
    entitlement_sk INTEGER REFERENCES dim_entitlements(entitlement_sk),
    partner_credit_sk INTEGER REFERENCES dim_partner_credits(partner_credit_sk),
    benefit_sk INTEGER REFERENCES dim_benefits(benefit_sk),
    benefit_order_sk INTEGER REFERENCES dim_benefit_orders(benefit_order_sk),
    availability_sk INTEGER REFERENCES dim_availabilities(availability_sk),

    usage_date DATE,
    resource_uri VARCHAR,
    effective_unit_price DECIMAL,
    unit_price DECIMAL,
    quantity DECIMAL,
    billing_pre_tax_total DECIMAL,
    billing_currency VARCHAR,
    pricing_pre_tax_total DECIMAL,
    pricing_currency VARCHAR,
    pc_to_bc_exchange_rate DECIMAL,
    pc_to_bc_exchange_rate_date DATE,
    service_info_1 VARCHAR,
    service_info_2 VARCHAR,
    tags JSON,
    additional_info JSON
);

