CREATE TABLE fact_charges (
    charge_sk BIGSERIAL PRIMARY KEY,

    partner_sk INTEGER,
    months_charge_date_sk INTEGER,
    customer_sk INTEGER,
    meter_sk INTEGER,
    product_sk INTEGER,
    sku_sk INTEGER,
    publisher_sk INTEGER,
    subscription_sk INTEGER,
    resource_location_sk INTEGER,
    resource_group_sk INTEGER,
    service_sk INTEGER,
    charge_type_sk INTEGER,
    unit_type_sk INTEGER,
    entitlement_sk INTEGER,
    partner_credit_sk INTEGER,
    benefit_sk INTEGER,
    benefit_order_sk INTEGER,
    availability_sk INTEGER,
    usage_date_sk INTEGER,
    billing_currency_sk INTEGER,
    pricing_currency_sk INTEGER,

    resource_uri VARCHAR,
    effective_unit_price DECIMAL,
    unit_price DECIMAL,
    quantity DECIMAL,
    billing_pre_tax_total DECIMAL,
    pricing_pre_tax_total DECIMAL,
    pc_to_bc_exchange_rate DECIMAL,
    pc_to_bc_exchange_rate_date DATE,
    service_info_1 VARCHAR,
    service_info_2 VARCHAR,
    tags VARCHAR,
    additional_info VARCHAR
);

